trigger:
  - master

jobs:
- job: Build
  timeoutInMinutes: 0

  pool:
    vmImage: ubuntu-latest

  variables:
    gcc: 'gcc-11.2.0'
    openwrtRelease: '22.03.1'
    workingDirectory: '$(Build.SourcesDirectory)/openwrt'

  steps:
  - script: sudo apt-get -q -y install libncurses-dev
    displayName: 'Install dependencies'

  - script: |
      umask 0022
      git clone https://github.com/openwrt/openwrt.git
    displayName: 'Clone OpenWrt git repo'

  - script: git checkout v$(openwrtRelease)
    workingDirectory: $(workingDirectory)
    displayName: 'Checkout v$(openwrtRelease)'

  - script: wget https://downloads.openwrt.org/releases/$(openwrtRelease)/targets/x86/64/openwrt-toolchain-$(openwrtRelease)-x86-64_$(gcc)_musl.Linux-x86_64.tar.xz
    workingDirectory: $(workingDirectory)
    displayName: 'Download toolchain'

  - script: tar -xf openwrt-toolchain-$(openwrtRelease)-x86-64_$(gcc)_musl.Linux-x86_64.tar.xz
    workingDirectory: $(workingDirectory)
    displayName: 'Extract toolchain'

  - script: |
      VERSION=`cat version`
      echo OpenWrt version is $VERSION
      echo "##vso[task.setvariable variable=openwrtVersion]$VERSION"
    workingDirectory: $(workingDirectory)
    displayName: 'Get version'

  - script: |
      ./scripts/feeds update -a
      ./scripts/feeds install -a
    workingDirectory: $(workingDirectory)
    displayName: 'Update package feeds'

  - script: cat diffconfig >> $(workingDirectory)/.config
    displayName: 'Copy .config file'

  - script: make defconfig
    workingDirectory: $(workingDirectory)
    displayName: 'Make defconfig'

  - script: |
      sed -i 's!CONFIG_TOOLCHAIN_ROOT="/opt/cross/x86_64-unknown-linux-gnu"!CONFIG_TOOLCHAIN_ROOT="$(workingDirectory)/openwrt-toolchain-$(openwrtRelease)-x86-64_$(gcc)_musl.Linux-x86_64/toolchain-x86_64_$(gcc)_musl"!' .config
    workingDirectory: $(workingDirectory)
    displayName: 'Update toolchain'

  - script: |
      NPROC=`nproc`
      echo Number of CPUs is $NPROC
    displayName: 'Print number of CPUs'

  - script: make -j $(($(nproc)+1)) download
    workingDirectory: $(workingDirectory)
    displayName: 'Download sources'

  - script: make -j $(($(nproc)+1)) world
    workingDirectory: $(workingDirectory)
    displayName: 'make world'

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(workingDirectory)/bin/targets/x86/64
      contents: '*'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
      gitHubConnection: github.com_scottmckenzie
      repositoryName: scottmckenzie/openwrt-apu2c0-custom-build
      tagSource: manual
      tag: 'v$(openwrtRelease)_$(Build.BuildNumber)'
      assets: |
        $(Build.ArtifactStagingDirectory)/*
