trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  release: 'v19.07.3'
  
steps:
- script: sudo apt-get -q -y install libncursesw5-dev
  displayName: 'Install dependencies'

- script: |
    umask 0022
    git clone https://git.openwrt.org/openwrt/openwrt.git
  displayName: 'Clone OpenWrt git repo'

- script: |
    cp .config openwrt/
    cd openwrt/
  displayName: 'Copy .config file'

- script: git checkout $(release)
  displayName: 'Checkout $(release)'

- script: |
    ./scripts/feeds update -a
    ./scripts/feeds install -a
  displayName: Update package feeds

- script: make
  displayName: 'Build the project'

- task: CopyFiles@2
  inputs:
    contents: 'bin/targets/x86/64/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
