trigger:
  - master

jobs:
- job: Build
  timeoutInMinutes: 0

  pool:
    name: Default

  variables:
    openwrtRelease: 'openwrt-22.03'
    workingDirectory: '$(Build.SourcesDirectory)/openwrt'

  steps:
  - script: sudo apt-get -q -y install libncurses-dev
    displayName: 'Install dependencies'

  - script: |
      umask 0022
      git clone https://github.com/openwrt/openwrt.git
    displayName: 'Clone OpenWrt git repo'

  - script: git checkout $(openwrtRelease)
    workingDirectory: $(workingDirectory)
    displayName: 'Checkout $(openwrtRelease)'

  - script: |
      VERSION=`cat version`
      echo OpenWrt version is $VERSION
      echo "##vso[task.setvariable variable=openwrtVersion]$VERSION"
    workingDirectory: $(workingDirectory)
    displayName: 'Get version'

  - script: |
      ./scripts/feeds update -a
      ./scripts/feeds install -a
    workingDirectory: $(workingDirectory)
    displayName: 'Update package feeds'

  - script: |
      cp .config $(workingDirectory)
    displayName: 'Copy .config file'

  - script: |
      make defconfig
    workingDirectory: $(workingDirectory)
    displayName: 'Make defconfig'

  - script: |
      NPROC=`nproc`
      echo Number of CPUs is $NPROC
    displayName: 'Print number of CPUs'

  - script: |
      make -j`nproc`
    workingDirectory: $(workingDirectory)
    displayName: 'Build the project'

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(workingDirectory)/bin/targets/x86/64
      contents: '*'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
      gitHubConnection: github.com_scottmckenzie
      repositoryName: scottmckenzie/openwrt-apu2c0-custom-build
      tagSource: manual
      tag: '$(openwrtRelease)_$(Build.BuildNumber)'
      assets: |
        $(Build.ArtifactStagingDirectory)/*
